name: MonkeyJail
version: 'R0.1-SNAPSHOT'
main: me.dedushka.monkeyJail.MonkeyJail
api-version: '1.21.11'
softdepend:
  - SkinsRestorer

commands:
  monkey:
    description: Основная команда зоопарка
    usage: /<command>